export const restaurants = [
    {
        id: "1",
        dishName: "Veg Biryani",
          description: "A delightful and aromatic dish made with fragrant basmati rice, assorted vegetables, and a blend of spices. It's a popular Indian one-pot meal that's both flavorful and satisfying.",
        image:"https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHVsYW98ZW58MHx8MHx8fDA%3D",
        review:"4.5",
        price:"$25",
    },
    {
        id: "2",
        dishName: "Paneer Tikka",
        description: "Paneer tikka is a popular Indian appetizer made by marinating paneer (cottage cheese) in a mixture of yogurt and spices, then grilling it until it's perfectly charred and smoky.",
        image:"https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGlra2F8ZW58MHx8MHx8fDA%3D",
        review:"3.2",
        price:"$30",

    },
    {
        id: "3",
        dishName: "Mutton Curry",
        description: "Mutton curry is a rich and spicy dish prepared with tender pieces of mutton cooked in a flavorful gravy made from aromatic spices, onions, and tomatoes. It's a classic Indian curry known for its bold flavors.",
        image:"https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TXV0dG9uJTIwQ3Vycnl8ZW58MHx8MHx8fDA%3D",
        review:"4.0",
        price:"$12",
    },
    {
        id: "4",
        dishName: "Kerala Sadya",
        description: "Kerala Sadya is a traditional vegetarian feast from the South Indian state of Kerala. It features a variety of dishes, including rice, sambar, aviyal, thoran, and more, served on a banana leaf.",
        image:"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGxlYWYlMjBkaXNofGVufDB8fDB8fHww",
        review:"5.0",
        price:"$32",
    },
    {
        id: "5",
        dishName: "Greek Salad",
        description: "A Greek salad is a refreshing and healthy dish made with fresh cucumbers, tomatoes, red onions, Kalamata olives, feta cheese, and a dressing of olive oil and herbs. It's a popular Mediterranean salad.",
        image:"https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8R3JlZWslMjBTYWxhZHxlbnwwfHwwfHx8MA%3D%3D",
        review:"2.0",
        price:"$9",
    },
    {
        id: "6",
        dishName: "Pasta Carbonara",
        description: "Pasta carbonara is an Italian pasta dish known for its creamy sauce made from eggs, cheese, pancetta, and black pepper. It's a classic Roman dish that's simple yet incredibly satisfying.",
        image:"https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGFzdGElMjBDYXJib25hcmF8ZW58MHx8MHx8fDA%3D",
        review:"3.9",
        price:"$10",
    },
];